eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
java:
  runtime:
    version: 11
server:
  port: 8086
spring:
  application:
    name: Optimizer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/TripPlanner
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: tripplannersystem@gmail.com
    password: ywvoybbjbecepwht
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
