spring:
  application:
    name: upload-service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: oanhha2001@gmail.com
    password: oydlwnsgjxitbqca
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
